<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Authors>Ralf Guder</Authors>
    <Copyright>Copyright 2026 Ralf Guder</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
